booklist/urls.py
from django.urls import path, include

from . import views

app_name = 'booklist'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('book-import/', views.BookImportView.as_view(), name='book-import'),
    path('book-create-manually/', views.BookCreateView.as_view(), name='book-create-manually'),
    path('book/<int:id>/', views.BookDetailView.as_view(), name='book_detail'),
    path('book/<int:id>/update/', views.BookUpdateView.as_view(), name='book_update'),
    path('booksearchpag/', views.BookListViewSearchView.as_view(), name='booksearchpag'),
]

src_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('booklist.urls')),
]

booklist/models.py
from django.db import models


class Book(models.Model):
    title = models.CharField(max_length=200)
    authors_name = models.CharField(max_length=300)
    published_date = models.DateField(help_text="example: 2017-03-14")
    isbn13_number = models.CharField(max_length=15)
    page_number = models.IntegerField(blank=True, null=True)
    link_book_cover = models.URLField(null=True, blank=True)
    language_book = models.CharField(max_length=40)

    def __str__(self):
        return f'{self.title} {self.published_date}'

booklist/forms.py
from django import forms
from .models import Book


class DateInput(forms.DateInput):
    input_type = 'date'


class BookModelForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = (
            'title', 'language_book', 'published_date',
            'authors_name', 'isbn13_number', 'page_number', 'link_book_cover'
        )
        widgets = {
            'published_date': DateInput(),
        }


class InputFormFilter(forms.Form):
    published_date_from = forms.CharField(
        widget=forms.DateInput(
            format='%Y-%m-%d',
            attrs={'type': 'date'}
        ),
        required=False,
        label='Daty od ',
    )
    published_date_to = forms.CharField(
        widget=forms.DateInput(
            format='%Y-%m-%d',
            attrs={'type': 'date'}
        ),
        required=False,
        label='Daty do ',
    )
    title = forms.CharField(required=False,)
    language_book = forms.CharField(required=False,)
    authors_name = forms.CharField(required=False,)

    CHOICES = (
        ('ascending_title', 'sortowanie alfabetycznie po tytule'),
        ('descending_title', 'sortowanie nie alfabetycznie po tytule'),
        ('ascending_pub_date', 'rosnąco po datach publikacji'),
        ('descending_pub_date', 'malejąco po datach publikacji'),
        ('ascending_language_book', 'sortowanie alfabetycznie po jezyku ksiazki'),
        ('descending_language_book', 'sortowanie nie alfabetycznie po jezyku ksiazki'),
        ('ascending_page_number', 'sortowanie alfabetycznie po liczbie stron'),
        ('descending_page_number', 'sortowanie nie alfabetycznie po liczbie stron'),
    )
    ordering = forms.CharField(
        widget=forms.Select(choices=CHOICES),
        required=False,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        print('to sa fields w init: ')
        print(self.fields)


class InputFormSearch(forms.Form):
    search_field = forms.CharField(required=False,)
    CHOICES = (
        ('ascending_title', 'sortowanie alfabetycznie po tytule'),
        ('descending_title', 'sortowanie nie alfabetycznie po tytule'),
        ('ascending_language_book', 'sortowanie alfabetycznie po jezyku ksiazki'),
        ('descending_language_book', 'sortowanie nie alfabetycznie po jezyku ksiazki'),
        ('ascending_page_number', 'sortowanie alfabetycznie po liczbie stron'),
        ('descending_page_number', 'sortowanie nie alfabetycznie po liczbie stron'),
    )
    order_search = forms.CharField(
        widget=forms.Select(choices=CHOICES),
        required=False,
    )













































# -------------------------------------------------------------------------

# good example https://www.fullstackpython.com/django-forms-modelform-examples.html
# from django.forms import ModelForm
# from gears.widgets import DropdownSelectSubmit
# from proceedings.models import CameraReady
# EMPTY_VOLUME_LABEL = '(no volume)'
# class UpdateVolumeForm(ModelForm):
#
#     class Meta:
#         model = CameraReady
#         fields = ['volume']
    # widgets = {
    #     'volume': DropdownSelectSubmit(
    #         empty_label=EMPTY_VOLUME_LABEL,
    #         label_class='font-weight-normal dccn-text-small',
    #         empty_label_class='text-warning-18',
    #         nonempty_label_class='text-success-18',
    #     )
    # }
    #
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['volume'].queryset = self.instance.proc_type.volumes.all()
    #     self.fields['volume'].empty_label = EMPTY_VOLUME_LABEL

    # fields = ['ordering']
    # widgets = {'ordering': Select(choices=CHOICES)}
    # from django.forms import ModelForm, Textarea
    # widgets = {'name': Textarea(attrs={'cols': 80, 'rows': 20}),}
    # verbose_name = "E-Mail Address"  - we can use it as parameter in field

    # widgets = {'published_date': forms.DateInput(format='%Y-%m-%d', attrs={'type': 'date'})}
    # labels = {
    #     'name': _('Writer'),
    # }
    # help_texts = {
    #     'name': _('Some useful help text.'),
    # }
    # , null = True, blank = True


    # published_date_gte = forms.CharField(widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    # published_date_gte = forms.DateField(widget=forms.widgets.DateInput(format='%Y/%m/%d', attrs={'type': 'date'}))
    # DateField has optional argument  input_formats
    # default = '', blank = True

# DATE_INPUT_FORMATS = ('%d/%m/%Y', '%d-%m-%Y', '%Y-%m-%d')
# class MyModelForm(forms.ModelForm):
#     issue_date = forms.DateField(widget=forms.DateInput(format = '%d/%m/%Y'), input_formats=settings.DATE_INPUT_FORMATS)

booklist/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, TemplateView, CreateView, DetailView, UpdateView

from booklist.forms import BookModelForm
from booklist.models import Book
from booklist.utils_google_book_api import BooksImporterApi


class IndexView(ListView):
    template_name = 'booklist/index.html'
    context_object_name = 'booklist'
    model = Book

    def get_queryset(self):
        return Book.objects.all().order_by('-id')


class BookImportView(TemplateView):
    template_name = 'booklist/import_phrase.html'

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        phrase = request.POST.get('phrase', '')
        if not phrase:
            message = 'field is empty pls input some phrase'
            return render(request, 'booklist/import_failed.html', {'error_message': message})
        try:
            books_importer = BooksImporterApi(phrase)
            books_importer.run()
        except Exception as message:
            return render(request, 'booklist/import_failed.html', {'error_message': message})
        print(type(books_importer.objects))
        for book_preparation in books_importer.objects:
            books_importer.objects_books.append(
                Book(title=book_preparation['title'],
                     authors_name=book_preparation['authors'],
                     published_date=book_preparation['publishedDate'],
                     isbn13_number=book_preparation['isbn_13'],
                     page_number=book_preparation['pageCount'],
                     language_book=book_preparation['language'],
                     link_book_cover=book_preparation['link_book_cover'],
                     )
            )
        Book.objects.bulk_create(books_importer.objects_books)
        return render(request, 'booklist/import_success.html', {'amount': books_importer.how_many_objects()})


class BookCreateView(CreateView):
    template_name = 'booklist/book_create_form.html'
    form_class = BookModelForm
    queryset = Book.objects.all()
    success_url = reverse_lazy('booklist:index')

    def form_valid(self, form):
        # print('to jest cleaned data \n', form.cleaned_data)
        return super().form_valid(form)


class BookDetailView(DetailView):
    template_name = 'booklist/book_detail.html'

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Book, id=id_)


class BookUpdateView(UpdateView):
    template_name = 'booklist/book_update_form.html'
    form_class = BookModelForm

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Book, id=id_)

    def get_success_url(self):
        book_id = self.kwargs['id']
        return reverse_lazy('booklist:book_detail', kwargs={'id': book_id})

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)


class BookListViewSearchView(ListView):
    template_name = 'booklist/book_listview_filter_search.html'
    model = Book
    paginate_by = 5

    def get(self, request, *args, **kwargs):
        print('args: ', args)
        print('kwargs: ', kwargs)
        print('to jest request z get : ', request)
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        # search: https://learndjango.com/tutorials/django-search-tutorial
        queryset = super().get_queryset()
        # print(queryset)
        print('to jest title z request GET get: ', self.request.GET.get('title', ''))
        search_field = self.request.GET.get('search_field', '')
        print('to jest search field\n', search_field)
        if search_field:
            query = Q()
            query |= Q(title__icontains=search_field)
            query |= Q(authors_name__icontains=search_field)
            query |= Q(language_book__icontains=search_field)
            order_search_map = {
                'ascending_title': 'title',
                'descending_title': '-title',
                'ascending_page_number': 'page_number',
                'descending_page_number': '-page_number',
                'ascending_language_book': 'language_book',
                'descending_language_book': '-language_book',
            }
            queryset = queryset.order_by(order_search_map.get(self.request.GET.get('order_search')))
            return queryset.filter(query)
        query = Q()
        title = self.request.GET.get('title', '')
        if title:
            query &= Q(title__icontains=title)
        published_date_gte = self.request.GET.get('published_date_from', '')
        if published_date_gte:
            query &= Q(published_date__gte=published_date_gte)
        published_date_lte = self.request.GET.get('published_date_to', '')
        if published_date_lte:
            query &= Q(published_date__lte=published_date_lte)
        authors_name = self.request.GET.get('authors_name', '')
        if authors_name:
            query &= Q(authors_name__icontains=authors_name)
        language_book = self.request.GET.get('language_book', '')
        if language_book:
            query &= Q(language_book__icontains=language_book)
        # print('querysecik before filtered field added to filter:   \n', queryset)
        # print('to jest queryset: \n', queryset.filter(query))
        if self.request.GET.get('ordering'):
            order_map = {
                'ascending_title': 'title',
                'descending_title': '-title',
                'ascending_pub_date': 'published_date',
                'descending_pub_date': '-published_date',
                'ascending_page_number': 'page_number',
                'descending_page_number': '-page_number',
                'ascending_language_book': 'language_book',
                'descending_language_book': '-language_book',
            }
            queryset = queryset.order_by(order_map.get(self.request.GET.get('ordering')))
        return queryset.filter(query)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form_dict = {}
        form_dict_order = {}
        # print('czyli to jest context object_list:   ', context['object_list'], '\n i page obj: \n', context['page_obj'])
        form_dict.update(
            language_book=self.request.GET.get('language_book', ''),
            title=self.request.GET.get('title', ''),
            published_date_to=self.request.GET.get('published_date_to', ''),
            published_date_from=self.request.GET.get('published_date_from', ''),
            authors_name=self.request.GET.get('authors_name', ''),
            ordering=self.request.GET.get('ordering', 'descending_pub_date'),
        )
        form_dict_order.update(
            order_search=self.request.GET.get('order_search', 'ascending_title'),
        )
        context['form'] = InputFormFilter(initial=form_dict)
        context['form_search'] = InputFormSearch(initial=form_dict_order)
        if self.request.GET.get('search_field', ''):
            context['search_field_found'] = self.request.GET.get('search_field', '')
        _request_copy = self.request.GET.copy()
        parameters = _request_copy.pop('page', True) and _request_copy.urlencode()
        context['parameters'] = parameters
        return context

booklist/templates/booklist/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>book list app</title>
    </head>
    <body>
        <div>
          <a href="{% url 'booklist:book-import' %}">
                    Import new books</a>
        </div>
        <div>
          <a href="{% url 'booklist:book-create-manually' %}">
                    Add book manually </a>
        </div>
        <div>
          <a href="{% url 'booklist:index' %}">Book List APP home page</a>
        </div>
        <main>
            <div>
                <div>
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </main>
    </body>
</html>

booklist/templates/booklist/book_create_form.html
{% extends 'booklist/base.html' %}

{% block content %}

<form method="post">
  {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create">
</form>


{% endblock %}

booklist/templates/booklist/book_detail.html
{% extends 'booklist/base.html' %}

{% block content %}

<h1>Title:{{ object.title }}</h1>
        <ul>
                <li>
                    language_book: {{object.language_book}}
                </li>
                <li>
                    isbn13_number: {{ object.isbn13_number }}
                </li>
                <li>
                    published_date: {{object.published_date}}
                </li>
                 <li>
                    authors_name: {{object.authors_name}}
                </li>
                <li>
                    page_number: {{object.page_number}}
                </li>
                <li>
                    link_book_cover: {{object.link_book_cover}}
                </li>
        </ul>

        <a href="{% url 'booklist:book_update' object.id %}">Update</a>


{% endblock %}

booklist/templates/booklist/book_listview_filter_search.html
{% extends 'booklist/base.html' %}

{% block title %}
  Booklist filter search order
{% endblock title %}



{% block content %}



        <form method="GET">
            <h1>Books Search title/language/pagenumber order </h1>
            <div class="i-am-centered">
                {% if search_field_found %}
                    <p>Record for search phrase {{search_field_found}}</p>
                {% endif %}
                {{ form_search.as_p }}
                <button type="submit">Search</button>
            </div>
            <br>
            <h1>Books filter order </h1>
            <div>
                {{ form.as_p }}
                <button type="submit">Filter</button>
            </div>
        </form>

<br>

    {% if object_list %}
        <div>
            <table>
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">title</th>
                    <th scope="col">created</th>
                    <th scope="col">language</th>
                    <th scope="col">authors</th>
                    <th scope="col">pages</th>
                    <th scope="col">isbn</th>
                    <th scope="col">published</th>
                    <th scope="col">go to book detail</th>
                  </tr>
                </thead>
            {% for book in object_list %}
                <tbody>
                  <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ book.title }}</td>
                    <td>{{ book.created |date:"Y-m-d" }}</td>
                    <td>{{ book.language_book }}</td>
                    <td>{{ book.authors_name }}</td>
                    <td>{{ book.page_number }}</td>
                    <td>{{ book.isbn13_number }}</td>
                    <td>{{ book.published_date }}</td>
                    <td><a href="{% url 'booklist:book_detail' book.id %}">{{ book.title }}</a></td>
                  </tr>
                </tbody>
            {% endfor %}
            </table>
        </div>

    {% endif %}

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1&{{ parameters }}">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}&{{ parameters }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}&{{ parameters }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}&{{ parameters }}">last &raquo;</a>

            {% endif %}
        </span>
    </div>


{% endblock %}

booklist/templates/booklist/book_update_form.html
{% extends 'booklist/base.html' %}

{% block content %}

<form method="post">
  {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" class="btn btn-default">
</form>


{% endblock %}

booklist/templates/booklist/import_failed.html
{% extends 'booklist/base.html' %}

{% block content %}

    {% if error_message %}

        <strong style="color:#C25100;">Error:</strong> <br>
        {{error_message}}<br><br><br>
        <fieldset>
            <form method="POST">
                {% csrf_token %}
                <label>Import title of book: </label><br>
                <input type="text" name="phrase">
                <button type="submit">Send</button>
            </form>
        </fieldset>
        <br><br>
    {% endif %}
    <div>
        <strong style="color:#C25100;">Menu:<br></strong>
        <li>
            <a href="{% url 'booklist:index' %}">go home-page</a><br>
        </li>
        <li>
            <a href="{% url 'booklist:book-import' %}">Try again</a><br>
        </li>
    </div>

{% endblock %}

booklist/templates/booklist/import_phrase.html
{% extends 'booklist/base.html' %}

{% block content %}

    <fieldset>
        <form method="POST">
            {% csrf_token %}
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            <label>Import title of book: </label><br>
            <input type="text" name="phrase">
            <button type="submit">Send</button>
        </form>
    </fieldset>

{% endblock %}

booklist/templates/booklist/import_success.html
{% extends 'booklist/base.html' %}

{% block content %}

    {% if amount > 0 %}
        <p>its great you imported completely {{amount}} of books to db</p>
        <li>
            <a href="{% url 'booklist:index' %}"> Go to homepage</a> <br>
        </li>
        <li>
            <a href="{% url 'booklist:book-import' %}"> Import more books </a>
        </li>


    {% else %}

        No books added. <br>
        Your phrase didn't match to conditions of add to db or something went wrong with criteria save in db.
        <br>
        Try again with other phrase.
        <a href="{% url 'booklist:book-import' %}">Import books</a>

    {% endif %}

{% endblock %}

booklist/templates/booklist/index.html
{% extends 'booklist/base.html' %}


{% block content %}

    {% if message %}
        message:
        <p>{{message}}</p>
    {% endif %}

    {% if booklist %}
        <ul>
            {% for book in booklist %}
                <li> <h4>{{book.title}}</h4></li>
{#                <a href="{% url 'booklist:book_detail' book.id %}" > Detail</a>#}
{#                <a href="{% url 'booklist:book_update' book.id %}" > Update</a>#}
            {% endfor %}
        </ul>

    {% else %}
        <p>No books are available.</p>
    {% endif %}

    <div >
        <span >
            {% if page_obj.has_previous %}
                <a href="?page=1">first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span >
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}"></a>

            {% endif %}
        </span>
    </div>
{% endblock %}